# APP DEPLOYMENT

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: demo
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      run: demo-exposed
  template:
    metadata:
      labels:
        run: demo-exposed
    spec:
      containers:
      - image: demo:v1
        name: demo
        ports:
        - containerPort: 8100
          protocol: TCP

---

# APP SERVICE

apiVersion: v1
kind: Service
metadata:
  labels:
    run: demo
  name: demo
spec:
  ports:
  - port: 8100
    protocol: TCP
    targetPort: 8100
  selector:
    run: demo-exposed
  type: NodePort